name: Damzaky, A person
markdown: kramdown
collections:
  cole:
    output: true
    permalink: /:collection/:title
  ano:
    output: true
    permalink: /:collection/:title
  demo:
    output: true
    permalink: /:collection/:title
  generator:
    output: true
    permalink: /:collection/:title
