name: Build and Deploy Jekyll Site

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby 3.0 (required by github-pages)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      - name: Install dependencies
        run: |
          gem install bundler
          bundle config set path 'vendor/bundle'
          bundle install

      - name: Generate GitHub Pages Repo List
        run: |
          USERNAME="${{ github.repository_owner }}"
          mkdir -p _data
          echo "[" > _data/pages_repos.json
          FIRST=1
          for repo in $(gh repo list $USERNAME --limit 1000 --json name --jq '.[].name'); do
            if [[ "$repo" == "${USERNAME}.github.io" ]]; then continue; fi
            if gh api "repos/$USERNAME/$repo/pages" &>/dev/null; then
              [ $FIRST -eq 0 ] && echo "," >> _data/pages_repos.json
              echo "{\"name\": \"$repo\", \"url\": \"https://$USERNAME.github.io/$repo/\"}" >> _data/pages_repos.json
              FIRST=0
            fi
          done
          echo "]" >> _data/pages_repos.json
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Jekyll Site
        run: bundle exec jekyll build

      - name: Generate urls.txt from repo list
        run: jq -r '.[].url' _data/pages_repos.json > urls.txt

      - name: Append repo URLs to sitemap.xml
        run: |
          SITEMAP_FILE="_site/sitemap.xml"
          TMP_FILE="_site/sitemap.temp.xml"
          cp "$SITEMAP_FILE" "$TMP_FILE"

          awk '
            /<\/urlset>/ {
              while ((getline url < "urls.txt") > 0) {
                print "  <url><loc>" url "</loc></url>"
              }
              close("urls.txt")
            }
            { print }
          ' "$TMP_FILE" > "$SITEMAP_FILE"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
