name: Build and Deploy Jekyll Site

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install Jekyll
        run: sudo gem install jekyll bundler
      
      - name: Generate GitHub Pages Repo List
        run: |
          USERNAME="damzaky"
          PAGES_REPO="${USERNAME}.github.io"
          
          mkdir -p _data
          echo "[" > _data/pages_repos.json
          FIRST=1
      
          for repo in $(gh repo list $USERNAME --limit 1000 --json name --jq '.[].name'); do
            if [[ "$repo" == "$PAGES_REPO" ]]; then
              continue
            fi
      
            if gh api "repos/$USERNAME/$repo/pages" &>/dev/null; then
              [ $FIRST -eq 0 ] && echo "," >> _data/pages_repos.json
              echo "{\"name\": \"$repo\", \"url\": \"https://$USERNAME.github.io/$repo/\"}" >> _data/pages_repos.json
              FIRST=0
            fi
          done
      
          echo "]" >> _data/pages_repos.json

      - name: Build Jekyll Site
        run: jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
