name: Manual Deploy All with Google Analytics

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current site
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: sudo apt install gh -y

      - name: Auth GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Get eligible repos
        run: |
          mkdir -p sites
          cd sites

          # List only repos that have GitHub Pages enabled
          gh repo list damzaky --limit 1000 --json name --jq '.[].name' > ../repos.txt
          echo "" > ../eligible.txt

          while read repo; do
            echo "Checking $repo"
            if [ -z "$repo" ]; then
              echo "⚠️ Skipping empty repo name"
              continue
            fi
            if gh api repos/damzaky/$repo/pages &> /dev/null; then
              branch=$(gh api repos/damzaky/$repo/pages --jq .source.branch)
             if [ -n "$branch" ]; then
                echo "$repo $branch" >> eligible.txt
              fi
            fi
          done < ../repos.txt

      - name: Clone, Inject, Copy
        run: |
          cd sites
          echo "---- eligible.txt ----"
          cat ../eligible.txt
          echo "----------------------"
          GA_ID=${{ vars.GA_MEASUREMENT_ID }}
          
          GA_SCRIPT="<script async src=\"https://www.googletagmanager.com/gtag/js?id=$GA_ID\"></script>
          <script>
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag(\"js\", new Date());
            gtag(\"config\", \"$GA_ID\");
          </script>"

          echo "Listing files:"
          ls -la

          while read repo branch; do
            echo "Processing $repo ($branch)"
            gh repo clone damzaky/$repo
            cd $repo
            git checkout $branch

            mkdir -p ../../$repo
            cp -r * ../../$repo/ || true

            find ../../$repo -name "*.html" -exec sed -i "/<\/head>/i $GA_SCRIPT" {} +

            cd ..
          INPUT_FILE=$(realpath ../eligible.txt)
          while IFS=' ' read -r repo branch || [ -n "$repo" ]; do
            ...
          done < "$INPUT_FILE"

      - name: Clean old files (except .git and .github)
        run: |
          find . -mindepth 1 -maxdepth 1 ! -name ".git" ! -name ".github" ! -name "sites" -exec rm -rf {} +

      - name: Move new files to root
        run: |
          mv sites/* .

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Manual deploy of all repos with GA" || echo "No changes to commit"
          git push origin main
