name: Update Repos List

on:
  workflow_dispatch:   # Allows manual runs

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install pyyaml requests

      - name: Fetch public non-fork repos
        env:
          GH_USER: damzaky
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python3 <<EOF
          import requests, yaml, os

          headers = {
              "Authorization": f"token {os.getenv('GH_TOKEN')}",
              "Accept": "application/vnd.github+json"
          }
          url = f"https://api.github.com/users/{os.getenv('GH_USER')}/repos?per_page=100&type=owner"
          repos = requests.get(url, headers=headers).json()

          data = [
              {
                  'name': repo['name'],
                  'homepage': repo['html_url']
              }
              for repo in repos if not repo.get('fork')
          ]

          with open("_data/repos.yml", "w") as f:
              yaml.dump(data, f, sort_keys=False)
          EOF

      - name: Commit changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add _data/repos.yml
          git commit -m "Update repos list" || echo "No changes"
          git push
